### ISSUE TITLE
httpx.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by pootispenserhere4723** [solsticegamestudios/GModCEFCodecFix#108]
```
Traceback (most recent call last):
  File "httpx/_transports/default.py", line 69, in map_httpcore_exceptions
  File "httpx/_transports/default.py", line 233, in handle_request
  File "httpcore/_sync/connection_pool.py", line 216, in handle_request
  File "httpcore/_sync/connection_pool.py", line 196, in handle_request
  File "httpcore/_sync/connection.py", line 101, in handle_request
  File "httpcore/_sync/http11.py", line 143, in handle_request
  File "httpcore/_sync/http11.py", line 113, in handle_request
  File "httpcore/_sync/http11.py", line 186, in _receive_response_headers
  File "httpcore/_sync/http11.py", line 224, in _receive_event
  File "httpcore/_backends/sync.py", line 124, in read
  File "contextlib.py", line 158, in __exit__
  File "httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 617, in <module>
  File "httpx/_api.py", line 198, in get
  File "httpx/_api.py", line 106, in request
  File "httpx/_client.py", line 827, in request
  File "httpx/_client.py", line 914, in send
  File "httpx/_client.py", line 942, in _send_handling_auth
  File "httpx/_client.py", line 979, in _send_handling_redirects
  File "httpx/_client.py", line 1015, in _send_single_request
  File "httpx/_transports/default.py", line 232, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "httpx/_transports/default.py", line 86, in map_httpcore_exceptions
httpx.ReadTimeout: The read operation timed out
[7801] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
Press Enter to continue...
```

**Comment by WinterPhoenix** [comment]
This was fixed in https://github.com/solsticegamestudios/GModCEFCodecFix/commit/9b08f9f5719f44c3d0a0cbf10ee4ca86e6fb2a12, but we haven't built a new release that includes it yet. Will update once it's out.

**Comment by pootispenserhere4723** [comment]
Oh i see, thanks for the info

**Comment by pootispenserhere4723** [comment]
I want to reopen this real quick
Apparently launching the thing with the `-a 0 ` parameters that i found in the website's install tutorial (https://www.solsticegamestudios.com/fixmedia/linux/) actually makes the fix work, now it's all working

**Comment by WinterPhoenix** [comment]
Auto-mode has no effect on how quickly network requests happen. Something else, network-wise, changed.
