### ISSUE TITLE
Hanging and failing on "fixing files" (MacOS Ventura 13.1)

### ISSUE THREAD

**Issue by davidburke2500** [solsticegamestudios/GModCEFCodecFix#118]
Hi

When I try running this (using the latest release) it seems to hang on the first file in the "fixing files" process for several minutes before failing due to an "unhandled exception". I'll paste below exactly what I'm getting on my terminal:

Fixing Files...
	Downloading: https://media.githubusercontent.com/media/solsticegamestudios/GModCEFCodecFix/master/darwin/x86-64/GarrysMod_Signed.app/Contents/Frameworks/Chromium%20Embedded%20Framework.framework/Chromium%20Embedded%20Framework.bsdiff...
Traceback (most recent call last):
  File "httpx/_transports/default.py", line 69, in map_httpcore_exceptions
  File "httpx/_transports/default.py", line 113, in __iter__
  File "httpcore/_sync/connection_pool.py", line 367, in __iter__
  File "httpcore/_sync/connection_pool.py", line 363, in __iter__
  File "httpcore/_sync/http11.py", line 349, in __iter__
  File "httpcore/_sync/http11.py", line 341, in __iter__
  File "httpcore/_sync/http11.py", line 210, in _receive_response_body
  File "httpcore/_sync/http11.py", line 224, in _receive_event
  File "httpcore/_backends/sync.py", line 124, in read
  File "contextlib.py", line 158, in __exit__
  File "httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 606, in <module>
  File "httpx/_api.py", line 198, in get
  File "httpx/_api.py", line 106, in request
  File "httpx/_client.py", line 827, in request
  File "httpx/_client.py", line 928, in send
  File "httpx/_client.py", line 922, in send
  File "httpx/_models.py", line 813, in read
  File "httpx/_models.py", line 829, in iter_bytes
  File "httpx/_models.py", line 883, in iter_raw
  File "httpx/_client.py", line 126, in __iter__
  File "httpx/_transports/default.py", line 112, in __iter__
  File "contextlib.py", line 158, in __exit__
  File "httpx/_transports/default.py", line 86, in map_httpcore_exceptions
httpx.ReadTimeout: The read operation timed out
[36610] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
Press Enter to continue.../Applications/GModCEFCodecFix.app 

does anyone have any idea how to resolve this?
TIA 🙏

**Comment by davidburke2500** [comment]
Ok so, it just fixed the file by itself after about 20 minutes, I guess I just had to give it some time lol
