### ISSUE TITLE
Patcher fails to install something

### ISSUE THREAD

**Issue by blockplace1232** [solsticegamestudios/GModCEFCodecFix#142]
It spits out this error and I have no idea what it means: 

It says "Fixing files" right after it says a bunch need fixing

Fixing Files...
	Downloading: https://media.githubusercontent.com/media/solsticegamestudios/GModCEFCodecFix/master/linux/x86-64/bin/linux64/chromium_process.bsdiff...
Traceback (most recent call last):
  File "httpx/_transports/default.py", line 72, in map_httpcore_exceptions
  File "httpx/_transports/default.py", line 236, in handle_request
  File "httpcore/_sync/connection_pool.py", line 216, in handle_request
  File "httpcore/_sync/connection_pool.py", line 196, in handle_request
  File "httpcore/_sync/connection.py", line 99, in handle_request
  File "httpcore/_sync/connection.py", line 76, in handle_request
  File "httpcore/_sync/connection.py", line 122, in _connect
  File "httpcore/_backends/sync.py", line 205, in connect_tcp
  File "contextlib.py", line 158, in __exit__
  File "httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ConnectTimeout: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 638, in <module>
  File "httpx/_api.py", line 210, in get
  File "httpx/_api.py", line 118, in request
  File "httpx/_client.py", line 837, in request
  File "httpx/_client.py", line 926, in send
  File "httpx/_client.py", line 954, in _send_handling_auth
  File "httpx/_client.py", line 991, in _send_handling_redirects
  File "httpx/_client.py", line 1027, in _send_single_request
  File "httpx/_transports/default.py", line 235, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "httpx/_transports/default.py", line 89, in map_httpcore_exceptions
httpx.ConnectTimeout: [Errno 110] Connection timed out
[PYI-19164:ERROR] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
Press Enter to continue...

**Comment by WinterPhoenix** [comment]
The line "Connection timed out" is what's important. Basically you're having trouble connecting to GitHub.

Check out the FAQ section on connection errors:
https://www.solsticegamestudios.com/fixmedia/faq/

**Comment by blockplace1232** [comment]
I'm using Arch Linux and there are no convient downloads for vpns for the links you provided as all linux versions are for ubuntu or fedora/RH based distributions

**Comment by WinterPhoenix** [comment]
Duplicate of #139

**Comment by blockplace1232** [comment]
Oh yea if you are having this issue I would recommend connecting to a different network
