### ISSUE TITLE
httpcore.ConnectError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by thekirbykid20067** [solsticegamestudios/GModCEFCodecFix#145]
Trying to install GModCEFCodecFix for the first time on a new computer and the exe gives this error every time I try to run it.

Fixing Files...
        Downloading: https://media.githubusercontent.com/media/solsticegamestudios/GModCEFCodecFix/master/win32/x86-64/bin/chrome_elf.dll.bsdiff...
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 72, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 236, in handle_request
  File "httpcore\_sync\connection_pool.py", line 216, in handle_request
  File "httpcore\_sync\connection_pool.py", line 196, in handle_request
  File "httpcore\_sync\connection.py", line 99, in handle_request
  File "httpcore\_sync\connection.py", line 76, in handle_request
  File "httpcore\_sync\connection.py", line 154, in _connect
  File "httpcore\_backends\sync.py", line 152, in start_tls
  File "contextlib.py", line 158, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 638, in <module>
  File "httpx\_api.py", line 210, in get
  File "httpx\_api.py", line 118, in request
  File "httpx\_client.py", line 837, in request
  File "httpx\_client.py", line 926, in send
  File "httpx\_client.py", line 954, in _send_handling_auth
  File "httpx\_client.py", line 991, in _send_handling_redirects
  File "httpx\_client.py", line 1027, in _send_single_request
  File "httpx\_transports\default.py", line 235, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "httpx\_transports\default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: [WinError 10054] An existing connection was forcibly closed by the remote host
[PYI-20448:ERROR] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!

**Comment by WinterPhoenix** [comment]
Please read the FAQ on connection errors:
https://solsticegamestudios.com/fixmedia/faq/

**Comment by WinterPhoenix** [comment]
Duplicate of #139
