### ISSUE TITLE
Support for disconnect network drives

### ISSUE THREAD

**Issue by PatrykZah** [solsticegamestudios/GModCEFCodecFix#24]
When it iterates through all drives its fails miserably at the ones that are network but disconnected.

First proposal would be to let us pass the path parameters.
Second would be to better handle this error by detect if its network drive, then skipping that drive if disconnected.

```
Steam Path:
M:\Steam

Traceback (most recent call last):
  File "ntpath.py", line 647, in realpath
FileNotFoundError: [WinError 53] The network path was not found: 'H:\\SteamLibrary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 240, in <module>
  File "ntpath.py", line 651, in realpath
  File "ntpath.py", line 601, in _getfinalpathname_nonstrict
FileNotFoundError: [WinError 53] The network path was not found: 'H:\\SteamLibrary'
[14576] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
Press Enter to not continue...
```

**Comment by WinterPhoenix** [comment]
This should be fixed in the [February 15th, 2022 Release](https://github.com/solsticegamestudios/GModCEFCodecFix/releases)
